# Generated by Django 4.1.7 on 2023-04-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("churchs", "0001_initial"),
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrator",
            name="church",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administrator",
                to="churchs.church",
                verbose_name="교회",
            ),
        ),
    ]
