from .accounts.accounts_view_set import AccountsViewSet
from .churchs.info_view_set import ChurchInfoViewSet
from .churchs.pastor_view_set import ChurchPastorViewSet
from .churchs.history_view_set import ChurchHistoryViewSet
from .churchs.notice_view_set import ChurchNoticeViewSet
from .churchs.weekly_view_set import ChurchWeeklyViewSet
from .churchs.member_view_set import ChurchMemberViewSet
from .churchs.calendar_view_set import ChurchCalendarViewSet
from .churchs.worship_schedule_view_set import ChurchWorshipScheduleViewSet
from .churchs.directions_view_set import ChurchDirectionsViewSet
