from .view_set import ChurchViewSet
from .pastor_view_set import ChurchPastorViewSet
from .notice_view_set import ChurchNoticeViewset
from .history_view_set import ChurchHistoryViewSet
from .weekly_view_set import ChurchWeeklyViewSet
from .worship_schedule_view_set import ChurchWorshipScheduleViewSet
from .calendar_view_set import ChurchCalendarViewSet
