# Generated by Django 4.1.7 on 2023-04-11 02:16

import apps.churchs.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("administrators", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Church",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 pk",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="ex) 여의도 순복음교회",
                        max_length=50,
                        null=True,
                        verbose_name="교회명",
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="교회 연락처"
                    ),
                ),
                (
                    "introduction_title",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="교회 소개글 제목"
                    ),
                ),
                (
                    "introduction_content",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="교회 소개글 내용"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="교회 주소"
                    ),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="교회 상세 주소"
                    ),
                ),
                (
                    "longitude",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="교회 주소 저장 시 자동으로 채워짐",
                        max_length=50,
                        null=True,
                        verbose_name="경도",
                    ),
                ),
                (
                    "latitude",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="교회 주소 저장 시 자동으로 채워짐",
                        max_length=50,
                        null=True,
                        verbose_name="위도",
                    ),
                ),
                (
                    "bible_edition",
                    models.CharField(
                        blank=True,
                        choices=[("KRB", "개역한글판"), ("NKR72H", "개역개정판")],
                        default="KRB",
                        max_length=20,
                        null=True,
                        verbose_name="성경판",
                    ),
                ),
                (
                    "is_exposure",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="교회 공개 여부"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.churchs.models.thumbnail_upload_url,
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.churchs.models.logo_upload_url,
                        verbose_name="로고",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
            options={
                "verbose_name": "2.1 교회 정보",
                "verbose_name_plural": "2.1 교회 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchDenomination",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 종파 pk",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="교회 종파 이름",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.3 교회 종파 정보",
                "verbose_name_plural": "2.3 교회 종파 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchWorshipSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 예배 일정 정보 pk",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="예배 일정 제목"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="예배 일정 소제목"
                    ),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        blank=True,
                        help_text="일요일: -1, 월요일: 0, ~ 토요일: 5",
                        null=True,
                        verbose_name="요일",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="예배 장소"
                    ),
                ),
                (
                    "mc",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="예배 진행자"
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="예배 대상"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="예배 참고"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="시작 시간"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료 시간"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_worship_schedule",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.9 교회 예배 일정 정보",
                "verbose_name_plural": "2.9 교회 예배 일정 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchWeekly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 주보 정보 pk",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="주보 제목"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.churchs.models.weekly_upload_url,
                        verbose_name="주보 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="주보 등록 날짜"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_weekly",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.7 교회 주보 정보",
                "verbose_name_plural": "2.7 교회 주보 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchPastor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 섬기는 이 pk",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="교회 섬기는 이 이름"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="교회 섬기는 이 직분(역할)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.churchs.models.pastor_upload_url,
                        verbose_name="섬기는 이 사진",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        blank=True, default=10000, verbose_name="섬기는 이 순서"
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_pastor",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.4 교회 섬기는 이 정보",
                "verbose_name_plural": "2.4 교회 섬기는 이 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 공지사항 정보 pk",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="공지사항 제목"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="공지사항 내용"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.churchs.models.notice_upload_url,
                        verbose_name="공지사항 사진",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="공지사항 등록 날짜"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_notice",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_notice",
                        to="administrators.administrator",
                        verbose_name="공지사항 작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.6 교회 공지사항 정보",
                "verbose_name_plural": "2.6 교회 공지사항 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 유저 중개 테이블 pk",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "등록 승인"),
                            ("confirm", "등록 심사 중"),
                            ("reject", "등록 거절"),
                        ],
                        default="confirm",
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_member",
                        to="accounts.account",
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_member",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.2 교회 회원 정보",
                "verbose_name_plural": "2.2 교회 회원 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 연혁 정보 pk",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="년도"
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="월"
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="일"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="연혁 내용"
                    ),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_history",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.5 교회 연혁 정보",
                "verbose_name_plural": "2.5 교회 연혁 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchDirections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="주차장"
                    ),
                ),
                (
                    "own_car",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="자가용"
                    ),
                ),
                (
                    "public_transport",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="대중교통"
                    ),
                ),
                (
                    "shuttle_bus",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="셔틀버스"
                    ),
                ),
                (
                    "church",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.1-1 교회 오시는 길 정보",
                "verbose_name_plural": "2.1-1 교회 오시는 길 정보",
            },
        ),
        migrations.CreateModel(
            name="ChurchCalendar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="교회 달력 정보 pk",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="일정 제목"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="일정 내용"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작 날짜"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료 날짜"),
                ),
                (
                    "church",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="church_calendar",
                        to="churchs.church",
                        verbose_name="교회",
                    ),
                ),
            ],
            options={
                "verbose_name": "2.8 교회 달력 정보",
                "verbose_name_plural": "2.8 교회 달력 정보",
            },
        ),
        migrations.AddField(
            model_name="church",
            name="denomination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="church",
                to="churchs.churchdenomination",
            ),
        ),
    ]
