# Generated by Django 4.1.7 on 2023-04-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("churchs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="churchweekly",
            name="month",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="월"
            ),
        ),
        migrations.AddField(
            model_name="churchweekly",
            name="year",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="년도"
            ),
        ),
    ]
