# Generated by Django 4.1.7 on 2023-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0002_churchweekly_month_churchweekly_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchcalendar',
            name='end_date',
            field=models.DateField(blank=True, default='', null=True, verbose_name='종료 날짜'),
        ),
    ]
