# Generated by Django 4.1.7 on 2023-05-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0003_alter_churchcalendar_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchhistory',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='년도'),
        ),
    ]
