# Generated by Django 4.1.7 on 2023-04-11 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="계정 pk",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="이름"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="전화번호",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="비밀번호"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=1,
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                (
                    "birth_year",
                    models.CharField(
                        blank=True,
                        help_text="ex) 19981021",
                        max_length=10,
                        null=True,
                        verbose_name="출생년도",
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="OS"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="기기 id"
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="앱 버전"
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="fcm 토큰"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="회원 가입 날짜"),
                ),
            ],
            options={
                "verbose_name": "1.1 회원 기본 정보",
                "verbose_name_plural": "1.1 회원 기본 정보",
            },
        ),
    ]
