# Generated by Django 4.1.7 on 2023-04-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="birth_year",
            new_name="birth_date",
        ),
        migrations.AddField(
            model_name="account",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "정상 계정"),
                    ("IN_ACTIVE", "비정상 계정"),
                    ("WAIT_FOR", "대기 중인 계정"),
                ],
                default="ACTIVE",
                max_length=15,
                verbose_name="회원 상태",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="전화번호"
            ),
        ),
    ]
